// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzsqlrzcvyunovzgolcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56c3Fscnpjdnl1bm92emdvbGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjE2NTksImV4cCI6MjA2ODM5NzY1OX0.OITZFFPdFcJOGTgD0wffFMiUVaKImP56cEL5QcJTPEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});